---
- name: Obtaining key for MySQL repository.
  apt_key:
    keyserver: pgp.mit.edu
    id: 5072E1F5

- name: Adding MySQL APT repository.
  apt_repository:
    repo: deb http://repo.mysql.com/apt/ubuntu xenial mysql-5.7
    state: present

- name: Installing MySQL package.
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - mysql-server
    - python-mysqldb

- name: Ensuring MySQL server is enabled and will start on boot.
  service:
    name: mysql
    state: started
    enabled: yes

- name: Setting root user password.
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    state: present
  with_items: "{{ mysql_root_hosts }}"

- name: Copying .my.cnf file for root.
  template:
    src: my.cnf.j2
    dest: ~/.my.cnf
    owner: root
    group: root
    mode: 0600
